### ISSUE TITLE
Jellyfin Compatibility

### ISSUE THREAD

**Issue by shawnshyguy** [dtankdempse/streamed-su-sports#1]
Don't know whether this falls as a feature request or a bug fix, but it seems like the the IPTV stream doesn't work under Jellyfin. I've tried all 4 URLs, but each one gives me following error:

<img width="359" alt="image" src="https://github.com/user-attachments/assets/a91eda3e-91e5-4939-b3bf-1301aea7b516">

Unfortunately it doesn't give me more info than that.

As far as setting the HTTP header, it seems like Jellyfin only lets you set a user agent header, so I can't do much there either.

Any suggestions or help is appreciated, thanks

**Comment by DrDmoney365** [comment]
I ran into the same issue. Here's how I got around that. Essentially, you have to use the user_agent header to inject the referrer header into the ffmpeg command. 

Under File/URL use - https://tinyurl.com/su-m3u1
Under user_agent use this exact string:
**" -referer "https://embedme.top/**

It works for me with these settings.
![image](https://github.com/user-attachments/assets/b3e83fb9-0a55-4503-a390-c41f0907a73e)

**Comment by dtankdempse** [comment]
Try using the proxied_playlist.m3u8 option that was just added to the main page.

**Comment by dtankdempse** [comment]
I tested the [the streamed-su-sports-proxy](https://github.com/dtankdempse/streamed-su-sports/blob/main/streamed-su-sports-proxy/README.md) with jellyfin and it worked.
