### ISSUE TITLE
403 Error on All Channels 

### ISSUE THREAD

**Issue by Spainguy77** [dtankdempse/streamed-su-sports#11]
Can no longer access channels for the past few days, getting the 403 error on TiviMate and all other iptv players. Note that channels can still be accessed directly thru the website. Seems new rules have been implemented to thwart this playlist?

**Comment by dtankdempse** [comment]
Changes have been made, and I'll look into it as soon as I have some time.

**Comment by Spainguy77** [comment]
> Changes have been made, and I'll look into it as soon as I have some time.

Playlist working again as a result of your timely and effective intervention 😉 You've already done so much, completely gratis, that I'm afraid to ask for more; but if it's at all possible, and is not too much of a bother, could you adjust the script to retrieve two streams, one HD and the other SD? 
In the previous iteration I  used a python script to change the number 1, which preceded playlist.m3u8, to 2 - 2 been the most common number for SD streams; alas it doesn't seem as straightforward in this version

**Comment by dtankdempse** [comment]
They probably made some more changes. I'll take a look at it again later when I have some more time.

**Comment by dtankdempse** [comment]
> > Changes have been made, and I'll look into it as soon as I have some time.
> 
> Playlist working again as a result of your timely and effective intervention 😉 You've already done so much, completely gratis, that I'm afraid to ask for more; but if it's at all possible, and is not too much of a bother, could you adjust the script to retrieve two streams, one HD and the other SD? In the previous iteration I used a python script to change the number 1, which preceded playlist.m3u8, to 2 - 2 been the most common number for SD streams; alas it doesn't seem as straightforward in this version

Yeah, I will look into adding some of the other links.

**Comment by Spainguy77** [comment]
> Yeah, I will look into adding some of the other links.

Ok, appreciate it
