### ISSUE TITLE
Doesn't work with VLC and TiViMate

### ISSUE THREAD

**Issue by Pljushevij** [dtankdempse/streamed-su-sports#13]
Hello
I was trying playlist vlc_playlist.m3u8 with VLC 3.0.20 - works only 1 channel.
I was trying playlist tivimate_playlist.m3u8 with TiViMate 5.1.0 - works only 1 channel.
With M3U-Playlist-Proxy (MPP) works perfectly. Why?

**Comment by dtankdempse** [comment]
As mentioned in the README file, the VLC, Kodi, and Tivimate playlists are no longer functional. To use the Streamed SU playlist, you need to run it through the m3u-playlist-proxy. If only one channel is working while using the proxy, there might be an issue with the setup. Could you provide more details about how you are running the MPP?
