### ISSUE TITLE
Support for Delta stream

### ISSUE THREAD

**Issue by MiniDuncan** [dtankdempse/streamed-su-sports#16]
It would make this so much better if it included the delta 1 backup as that is the one that almost always works when the alpha stream is down

**Comment by dtankdempse** [comment]
I’ll look into adding more links, but I wouldn’t want the playlist to become cluttered with duplicate events. It might be better to organize all the backup links under a single group called 'Mirrors.

**Comment by MiniDuncan** [comment]
cheers

**Comment by dtankdempse** [comment]
This has been added, labeled under the group "Mirror Links".
