### ISSUE TITLE
TiviMate setup/walkthrough

### ISSUE THREAD

**Issue by SquishyBewbz** [dtankdempse/streamed-su-sports#22]
Sorry in advance for my ignorance, But I have tried multiple times and I cannot seem to get this to work inside Tivimate.

Do you by chance have a similar setup guide for StreamedSU as you do for DaddyLive and MethStreams?

for example: (and anything special/extra that's required)
playlist:  bit.ly
epg:  bit.ly

again, sorry in advance. Thanks for your efforts.

**Comment by dtankdempse** [comment]
Streamed SU now uses tokenized streaming URLs. To use the playlist, you'll need the [m3u-playlist-proxy](https://github.com/dtankdempse/m3u-playlist-proxy). if you don't have a computer, you can use the Vercel option.

**Comment by SquishyBewbz** [comment]
Thanks, I figured it out following you Vercel guide
