### ISSUE TITLE
Tennis Channels Not Playing 

### ISSUE THREAD

**Issue by Spainguy77** [dtankdempse/streamed-su-sports#4]
Thanks for your great work! None of the Tennis channels is playing, also most of the football channels. Is there something I can do from my end to rectify this? I'm using the premium version of TiviMate.

**Comment by dtankdempse** [comment]
Actually, the issue is that [streamed.su](href.li/?https://streamed.su/schedule) lists events in their API response, but they never actually provide links for these events at the scheduled time. If you check their website under the Tennis section, you'll notice they don't have any streams playing. I assume they list these events with the intention of providing streams but are unable to find a link at the time of the event.

**Comment by Spainguy77** [comment]
> Actually, the issue is that [streamed.su](http://href.li/?https://streamed.su/schedule) lists events in their API response, but they never actually provide links for these events at the scheduled time. If you check their website under the Tennis section, you'll notice they don't have any streams playing. I assume they list these events with the intention of providing streams but are unable to find a link at the time of the event.

Appreciate your quick response. The issue is somewhat resolved: even though the playlist was recently refreshed I decided to refresh it again anyway, and now the channel I wanted to watch is now playing. Much thanks again for your invaluable work. Btw, is there a way to stream daddylive and moveonjoy in true hls, so that stream quality can be selected by end-user?

**Comment by dtankdempse** [comment]
Unfortunately, If the playlist doesn't provide quality options, it's not possible to stream at a different resolution or quality.

**Comment by Spainguy77** [comment]
> Unfortunately, If the playlist doesn't provide quality options, it's not possible to stream at a different resolution or quality.

Yes, I imagined as much, but was really thinking about re-streaming via a vm, on say Oracle. Although the free tier is very generous, I would expect donations from regular users. Anyways, something to think about
