### ISSUE TITLE
Encryption Key

### ISSUE THREAD

**Issue by TheManCashy** [dtankdempse/streamed-su-sports#6]
Hello, streams are no longer player "Failed to fetch encryption key: 404"

**Comment by dtankdempse** [comment]
Yeah it seems like the Cloudflare proxy is no longer working with streamed-su-sports. Might need to switch to another option. I will be releasing a vercel soon. Is that what you are using?

**Comment by dtankdempse** [comment]
Vercel has now been added as an option.
