### ISSUE TITLE
Streamed-su Proxy

### ISSUE THREAD

**Issue by TheManCashy** [dtankdempse/streamed-su-sports#8]
Hello, I know you created vercel proxy for playlist but I was wondering if you could create the same for the:
[worker.js](https://github.com/dtankdempse/streamed-su-sports/blob/main/streamed-su-sports-proxy/worker.js)

This one allowed to stream single m3u8 events and not the full playlist. Im not sure if that doable with the m3u-playlist-proxy you provided, I have tried many times and only allows to stream the [playlist.m3u8](https://github.com/dtankdempse/streamed-su-sports/blob/main/playlist.m3u8) not a single stream from streamed su.

**Comment by dtankdempse** [comment]
I'm not entirely sure I understand what you're aiming to do. Are you looking to enter a single stream URL into the text field rather than generating an entire playlist? Could you share a few examples to clarify?

**Comment by TheManCashy** [comment]
Hi, yes so for example I deployed [worker.js](https://github.com/dtankdempse/streamed-su-sports/blob/main/streamed-su-sports-proxy/worker.js) and i provided a single URL from [playlist.m3u8](https://github.com/dtankdempse/streamed-su-sports/blob/main/playlist.m3u8) 

example: {cf-domain}?url=https%3A%2F%2Frr.vipstreams.in%2Fcharlie%2Fjs%2F2024-players-championship-30-board-one-1629409158%2F1%2Fplaylist.m3u8&data={ref&user-agent-encoded}

Then was able to pass this Cloudflare URL into a html/JavaScript player and it would play the livestream. But with the vercel proxy it doesn't work, it only works with playlist.

**Comment by dtankdempse** [comment]
Could you let me know which JavaScript-based player you're using? Alternatively, feel free to message me on Discord, and I’ll do my best to replicate the issue. My Discord: dtanks_86578.
