### ISSUE TITLE
Can not play any m3u8 link

### ISSUE THREAD

**Issue by bongna** [dtankdempse/streamed-su-sports#9]
I deployed a worker Cloudflare, but I can not play any m3u8 link. Example
[https://](https://your-worker-name.workers.dev?url=https%3A%2F%2Frr.vipstreams.in%2Falpha%2Fjs%2Fone-friday-fights-85%2F1%2Fplaylist.m3u8&data=UmVmZXJlcj1odHRwczovL2VtYmVkbWUudG9wLw%3D%3D

**Comment by dtankdempse** [comment]
Cloudflare began returning a 403 error when attempting to fetch the encryption key, so I’ve decided to remove the Cloudflare option altogether. Please use the Vercel option I’ve added instead, which still offers a free tier. [m3u-playlist-proxy](https://github.com/dtankdempse/m3u-playlist-proxy).

**Comment by bongna** [comment]
so, can you provide help me config deploy Vercel?

**Comment by dtankdempse** [comment]
Log in to Vercel with your GitHub account and follow the video in the READ ME section.

**Comment by bongna** [comment]
Thanks, I have a question, how to get playlist from streameast?

**Comment by dtankdempse** [comment]
Their webpage is straightforward. For live events (or approximately 60 minutes before), they list the links directly on the page.

This page here:
`https://the.streameast.app/stream/lux/lux-047-live-stream`

Has a javascript with the source url:
`<html>
<body>

var player = new Clappr.Player({
--
  | source: window.atob('aHR0cHM6Ly9pbml0LmNsbWJvc2Vhbi5zcGFjZS9wbGF5bGlzdC8yNzI0Ni9sb2FkLXBsYXlsaXN0'),
  | autoPlay: false,
  | poster: '',
  | plugins: [],
  |  
  | mediacontrol: {seekbar: "#0053EF", buttons: "#FAFAFA"},
  | mimeType: "application/x-mpegURL",
  | width: '100%',
  | height: '360px',
  | events: {},
  | disableErrorScreen: false,
  | disableKeyboardShortcuts: true,
  | disableVideoTagContextMenu: false,
  | hlsRecoverAttempts: 4,
  | retryFailedSegments: false,
  | playback: {
  | hlsjsConfig: {
  | retryFailedSegments: false,
  | maxBufferSize: 0,       // Highly recommended setting in live mode
  | xhrSetup: function (xhr, url) {
  | xhr.timeout = 16500; // Set your desired timeout value in milliseconds
  | },
  | maxBufferLength: 5,     // Highly recommended setting in live mode
  | liveSyncDurationCount: 3,   // Highly recommended setting in live mode
  | }
  | }
  | });


</body>
</html>`
<br><br>

The source is simply a Base64 encoded string, which, when decoded, is:

Stream Url:
`https://init.clmbosean.space/playlist/27246/load-playlist`

Headers:
`Referer: https://the.streameast.app/`
`Origin: https://the.streameast.app`

Create a scraper to gather all event pages for the day. The playlist won’t contain direct links to the events, as these links only become available 60 minutes before each event. Instead, the m3u8 list will include a URL pointing to your script, with the event page passed as a parameter. This way, when a user tries to play the stream, the script accesses the event page in real time to retrieve the actual stream URL.

Example:
`http://my-script-site.workers.dev?url=https://the.streameast.app/stream/lux/lux-047-live-stream`

The script would then retrieve the stream URL from the event page and redirect the user directly to it.

**Comment by bongna** [comment]
Thanks @dtankdempse so much

**Comment by bongna** [comment]
Hi @dtankdempse, can you help me more details? Because I tried based on your suggestions above but I encounter error 403, then I am using through m3u8-playlist-proxy I encounter failed fetch list. Thanks @dtankdempse so much again

**Comment by dtankdempse** [comment]
To test a single stream url using the proxy, remove /playlist from the URL.

Example:
`http://localhost:4123?url=http%3A%2F%2Finit.clmbosean.space%2Fplaylist%2F27322%2Fload-playlist&data=VXNlci1BZ2VudD1Nb3ppbGxhLzUuMCAoaVBob25lOyBDUFUgaVBob25lIE9TIDE3XzcgbGlrZSBNYWMgT1MgWCkgQXBwbGVXZWJLaXQvNjA1LjEuMTUgKEtIVE1MLCBsaWtlIEdlY2tvKSBWZXJzaW9uLzE4LjAgTW9iaWxlLzE1RTE0OCBTYWZhcmkvNjA0LjF8UmVmZXJlcj1odHRwczovL3RoZS5zdHJlYW1lYXN0LmFwcC98T3JpZ2luPWh0dHBzOi8vdGhlLnN0cmVhbWVhc3QuYXBw`

To create a playlist, you'll need one script to scrape event pages and another to retrieve the streaming links. When I have some time, I'll look into adding this site.

**Comment by bongna** [comment]
Thanks @dtankdempse , let me see

**Comment by bongna** [comment]
do you know how to manually get a live link from streameast? or is there a tool for me to do it manually? thank you very much

**Comment by TheManCashy** [comment]
> do you know how to manually get a live link from streameast? or is there a tool for me to do it manually? thank you very much

Download an extension called m3u8 sniffer, visit one of the livestreams this will give you the live link.
